os:
  - osx

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2          ; fi

script: xcodebuild -project VirtualH89.xcodeproj/ -target VirtualH89

